platform:
  - x64

environment:
  global:
    CYG_ROOT: C:/cygwin
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin/var/cache/setup
  matrix:
    - OCAMLBRANCH: 4.02
    - OCAMLBRANCH: 4.03
    - OCAMLBRANCH: 4.04
  OCAMLROOT: C:/OCaml-%OCAMLBRANCH%

cache:
  - C:\OCaml-4.02
  - C:\OCaml-4.03
  - C:\OCaml-4.04

install:
  # Make sure the Cygwin path comes before the Git one (otherwise
  # cygpath behaves crazily), but after the MSVC one.
  - set Path=C:\cygwin\bin;%OCAMLROOT%\bin;%OCAMLROOT%\bin\flexdll;%Path%
  - '"%CYG_ROOT%\setup-x86.exe" -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P diffutils -P dos2unix -P gcc-core -P cygwin64-gcc-core -P mingw64-i686-gcc-core -P mingw64-x86_64-gcc-core -P make -P ncurses >NUL'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"

build_script:
  - "%CYG_ROOT%/bin/bash -lc \"echo 'eval $($APPVEYOR_BUILD_FOLDER/tools/msvs-promote-path)' >> ~/.bash_profile\""
  - '%CYG_ROOT%/bin/bash -lc "$APPVEYOR_BUILD_FOLDER/appveyor_build.sh"'

test: off
